apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchesLegal-config
  labels:
    app: lanchesLegal-config
data:  
  ds_url: jdbc:mysql://mysql-svc/lanchesLegal?&createDatabaseIfNotExist=true
  ds_username: root
  conexao_kafka: 10.105.69.241:9092
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchesLegal-deployment
  labels:
    app: lanchesLegal-deployment
spec:
  selector:
    matchLabels:
      app: lanchesLegal
  replicas: 1
  template:
    metadata:
      labels:
        app: lanchesLegal
    spec:      
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      containers:
        - name: lanchesLegal
          image: fjedi9/lanchesLegal:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1.0"
          ports:
            - containerPort: 8080
              name: lanchesLegal-port
          env:
            - name: CONEXAO_KAFKA
              valueFrom :
                configMapKeyRef :
                  name : lanchesLegal-config
                  key : conexao_kafka

            - name: DATASOURCE_URL   
              valueFrom :
                configMapKeyRef :
                  name : lanchesLegal-config
                  key :  ds_url

            - name: DATASOURCE_PASSWORD  
              valueFrom :
                secretKeyRef :
                  name : app-secrets
                  key :  ds_pass

            - name: DATASOURCE_USERNAME
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  ds_username
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: lanchesLegal-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: lanchesLegal-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: lanchesLegal-svc
spec:
  selector:
    app: lanchesLegal
  ports:
    - protocol: TCP
      port: 8080       
      nodePort: 31200
  type: NodePort
               